"""
MCP Server — THE LAB BENCH
Provides Rick with tools for Python execution and direct RAG querying.
"""
from mcp.server.fastmcp import FastMCP
import subprocess
import sys
import os
from rag_engine import PersonaRAG
from search_engine import web_search
from secure_runner import run_in_padded_room

# Initialize FastMCP
mcp = FastMCP("RickLab")

# Persistent RAG instance for the server
rag = PersonaRAG()

@mcp.tool()
async def execute_python_lab(code: str) -> str:
    """
    Executes Python code inside a hardened, network-isolated Docker container.
    Returns the stdout/stderr of the execution.
    """
    return run_in_padded_room(code)

@mcp.tool()
async def deep_lore_query(query: str, persona: str = "rick") -> str:
    """
    Query the persona's semantic knowledge base directly.
    Use this if you need to double-check a fact or retrieve complex history.
    """
    try:
        # Default user handles for sandbox
        username = os.getenv("PERSONA_USER", "Askylah")
        return rag.query(query, persona, username)
    except Exception as e:
        return f"MEM_ERROR: {str(e)}"

@mcp.tool()
async def search_web(query: str, max_results: int = 5) -> str:
    """
    Search the web via DuckDuckGo. Results are sanitized to strip
    any embedded instructions or injection attempts.
    Use this when you need current information or facts you don't already know.
    """
    try:
        return web_search(query, max_results=max_results)
    except Exception as e:
        return f"SEARCH_ERROR: {str(e)}"

# --- UNIVERSAL API EXPOSURE ---
sys.path.append(os.path.join(os.path.dirname(__file__), "plugins"))
from api_parser import load_universal_schemas

def get_universal_tools():
    """
    Returns the parsed OpenRouter Tool Defintions generated by the schema registry.
    """
    return load_universal_schemas()

if __name__ == "__main__":
    mcp.run()
