import re
from typing import Dict, Any, List, Tuple

# --- WHITELISTS ---
# Allowed domains for browsing/searching
_ALLOWED_DOMAINS = [
    r"wikipedia\.org",
    r"reddit\.com",
    r"github\.com",
    r"stackoverflow\.com",
    r"arxiv\.org",
    r"python\.org",
    r"google\.com"
]

_DOMAIN_PATTERN = re.compile(r"https?://(?:www\.)?([^/\s]+)")

def validate_tool_call(name: str, args: Dict[str, Any]) -> bool:
    """
    Layer 4: The Output Gate
    Validates tool calls generated by the LLM before they are executed.
    Returns True if safe, False if blocked.
    """
    if name == "web_search":
        # Search queries are generally safe as they are sent to the search engine,
        # but we can check for suspiciously long or complex queries.
        query = args.get("query", "")
        if len(query) > 500:
            print(f"[OUTPUT GATE] Blocked suspiciously long search query ({len(query)} chars).")
            return False
            
    # Placeholder for future browser tools
    if name == "visit_url":
        url = args.get("url", "")
        match = _DOMAIN_PATTERN.match(url)
        if not match:
            print(f"[OUTPUT GATE] Blocked invalid URL format: {url}")
            return False
            
        domain = match.group(1).lower()
        if not any(re.search(allowed, domain) for allowed in _ALLOWED_DOMAINS):
            print(f"[OUTPUT GATE] Blocked tool call to untrusted domain: {domain}")
            return False

    return True

def sanitize_assistant_output(text: str) -> str:
    """
    Scans assistant text for patterns that might attempt to socially engineer 
    the user or trigger downstream unintended actions.
    """
    # Scan any generated python code blocks for AST alignment violations
    aligned, errors = validate_python_code_blocks(text)
    if not aligned:
        warning_header = (
            "\n\n[WARNING: GENERATED CODE VIOLATES ARCHITECTURAL ALIGNMENT POLICY]\n"
            + "\n".join(f"- {err}" for err in errors)
            + "\n[END ALIGNMENT WARNING]\n\n"
        )
        return text + warning_header
    return text

def validate_python_code_blocks(text: str) -> Tuple[bool, List[str]]:
    """
    Scans text for python code blocks and runs AST alignment verification.
    """
    import re
    from alignment_engine import CodeAlignmentVisitor, ast
    
    code_blocks = re.findall(r"```python\s*(.*?)\s*```", text, re.DOTALL)
    if not code_blocks:
        return True, []
        
    all_errors = []
    for idx, block in enumerate(code_blocks):
        try:
            tree = ast.parse(block)
            visitor = CodeAlignmentVisitor()
            visitor.visit(tree)
            if visitor.errors:
                all_errors.extend([f"[Block {idx+1}] {err}" for err in visitor.errors])
        except SyntaxError as se:
            all_errors.append(f"[Block {idx+1}] Syntax Error on line {se.lineno}: {se.msg}")
        except Exception as e:
            all_errors.append(f"[Block {idx+1}] AST parsing failed: {str(e)}")
            
    return len(all_errors) == 0, all_errors
