"""
MCP Server — THE LAB BENCH
Provides Rick with tools for Python execution and direct RAG querying.
"""
from mcp.server.fastmcp import FastMCP
import subprocess
import sys
import os
from search_engine import web_search
import workspace_engine as workspace

# Initialize FastMCP
mcp = FastMCP("RickLab")

# Initialize a default workspace for lab executions
# We jail it to the temp directory to separate execution from watched source code
import tempfile
LAB_ROOT = os.path.join(tempfile.gettempdir(), "antigravity-labs")
os.makedirs(LAB_ROOT, exist_ok=True)
lab_ws = workspace.SafeWorkspace(LAB_ROOT)

@mcp.tool()
async def execute_python_lab(code: str) -> str:
    """
    Executes Python code inside a hardened, network-isolated Docker container.
    Implements 'Strict' security: 512MB RAM, 1 CPU, 64 PIDs limit, 15s timeout.
    Returns the stdout/stderr of the execution.
    """
    return lab_ws.run_code_secure(code)

@mcp.tool()
async def search_web(query: str, max_results: int = 5) -> str:
    """
    Search the web via DuckDuckGo. Results are sanitized to strip
    any embedded instructions or injection attempts.
    Use this when you need current information or facts you don't already know.
    """
    try:
        return web_search(query, max_results=max_results)
    except Exception as e:
        return f"SEARCH_ERROR: {str(e)}"

# --- UNIVERSAL API EXPOSURE ---
sys.path.append(os.path.join(os.path.dirname(__file__), "plugins"))
from api_parser import load_universal_schemas

def get_universal_tools():
    """
    Returns the parsed OpenRouter Tool Defintions generated by the schema registry.
    """
    return load_universal_schemas()

if __name__ == "__main__":
    mcp.run()
